services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Passwd_2"
      MSSQL_TELEMETRY_ENABLED: "FALSE"
      MSSQL_TELEMETRY_FREQUENCY: "NEVER"
    ports:
      - 1433:1433
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Passwd_2 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
  
  skizz:
    image: neuromagusdocker/skizz:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 5050:5050
      - 5051:5051
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=skizz;User Id=SA;Password=Passwd_2;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis
    volumes:
      - ./API/ssl/localhost.pfx:/app/localhost.pfx
    depends_on:
      mssql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  redis-data:
  sql-data:
    
