services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Passwd_2"
      MSSQL_TELEMETRY_ENABLED: "FALSE"
      MSSQL_TELEMETRY_FREQUENCY: "NEVER"
    ports:
      - 1433:1433